// Fun Fact: I drink a looot of water.
// Twitter: @anne_melody

print(" *                *            * ")
print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")

print("                       .--------.
print("  *               .    |________|        .          *       ")
print("                       |      __|/\                         ")
print("            *        .-'======\_\o/.                        ")
print("                    /___________<>__\                       ") 
print("              ||||||  /  (o) (o)  \                         ")
print("              |||||| |   _  O  _   |          .             ")
print("    .         |||||| |  (_)   (_)  |                        ")
print("              ||||||  \   '---'   /    *                    ")
print("              \====/   [~~~~~~~~~]                          ")
print("               \\//  _/~||~`|~~~~~\_                        ")
print("               _||-'`/  ||  |      \`'-._       *           ")
print("       *    .-` )|  ;   ||  |)      ;    '.                 ")
print("           /    `--.|   ||  |       |      `\               ")
print("          |         \   |||||)      |-,      \         .    ")
print("           \       .;       _       ; |_,    |              ")
print("            `'''||` ,\     (_)     /,    `.__/              ")
print("                ||.`  '.         .'  `.             *       ")
print("     *          ||       ` ' ' `       \                    ")
print("                ||                      ;                   ")
print("  .          *  ||                      |    .              ")
print("                ||                      |              *    ")
print("                ||                      |                   ")
print(".__.-""-.__.-"""||                      ;.-"""-.__.-""-.__. ")
print("                ||                     /                    ")
print("                ||'.                 .'                     ")
print("                ||  '-._  _ _  _ _.-'                       ")
print("               `""`                                         ")
